//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankNormal.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Currency_Type> Currency_Type { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Enter_type> Enter_type { get; set; }
        public virtual DbSet<EnterData> EnterData { get; set; }
        public virtual DbSet<Individual> Individual { get; set; }
        public virtual DbSet<LegalEntity> LegalEntity { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Score_type> Score_type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Transaction_type> Transaction_type { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountStatus> AccountStatus { get; set; }
    }
}
