//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankNormal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Number { get; set; }
        public int Currency { get; set; }
        public int Type { get; set; }
        public decimal Amount { get; set; }
        public int UserID { get; set; }
    
        public virtual Currency_Type Currency_Type { get; set; }
        public virtual Score_type Score_type { get; set; }
        public virtual Account Account { get; set; }
    }
}
